name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Lint
        run: forge fmt --check
